version: "3.9"

services:
  mongo:
    image: mongo
    container_name: db-mongo
    ports:
      - '27017:27017'

  app:
    build: .
    container_name: desafio-sharenergy
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app

volumes:
  mongo_volume:
    driver: local
      

  
    